server:
  port: 9001
  
spring:
  datasource:
  
    url: jdbc:mysql://localhost:3306/m1 
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password

  jpa:
    database-platform: org.hibernate.dialect.MySQL55Dialect
    hibernate:
      ddl-auto: update
      
        
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  application:    name: MICRO1    
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:    hostname: localhost  
    
    
 